name: 'Readling list data update'

on:
  push:
    branches:
      - main
  issues:
    types: [opened, edited, deleted]
  schedule:
    - cron: ' 0 0 * * * '

jobs:
  feed-processor:
    name: Update TIR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          npm install ejs -g
          npm install
      - name: Update issue data
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate HTML file
        run: |
          ejs template/index.ejs -f template/data.json -o template/output.html
      - name: Copy to dist folder
        run: |
          rm -rf dist
          mkdir dist
          cp template/* dist/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
